name: Sync Fork

on:
  schedule:
    - cron: '0 */12 * * *' # Sincroniza a cada 12 horas
  workflow_dispatch:      # Permite rodar manualmente clicando no botão

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permissão necessária para gravar as mudanças no seu repo
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Sync with Upstream
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh repo sync ByStartup-Desenvolvimento/soda-cristal-app --branch main
